import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:iconstruct/core/validation/password_policy.dart';
import 'package:iconstruct/features/auth/data/email_service.dart';
import 'package:iconstruct/features/auth/presentation/widgets/otp_dialog.dart';
import 'package:iconstruct/features/auth/data/auth_login_error.dart';
import 'package:iconstruct/core/widgets/app_message.dart';

class RegisterScreen extends StatefulWidget {
  const RegisterScreen({super.key});

  @override
  State<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends State<RegisterScreen> {
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();
  final _confirmPasswordController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  final EmailService _emailService = EmailService();

  bool _loading = false;
  bool _obscurePassword = true;
  bool _obscureConfirmPassword = true;
  bool _acceptedTerms = false;

  String? _emailError;
  String? _passwordError;
  String? _confirmPasswordError;

  final List<Map<String, String>> _termsAndConditions = const [
    {
      'title': '1. Purpose of iConstruct',
      'body':
          'iConstruct is a smart construction support system designed to help users plan basic residential construction projects through material estimation, cost estimation, project saving, supplier recommendations, and quotation support. The system is intended as a planning tool and should not replace professional construction, engineering, or architectural advice.',
    },
    {
      'title': '2. Accuracy of Material and Cost Estimates',
      'body':
          'All material quantities and cost estimates generated by iConstruct are for reference only. Actual construction costs may vary depending on supplier prices, labor costs, delivery fees, product availability, site conditions, and market changes. Users must verify estimates before making purchases or starting construction work.',
    },
    {
      'title': '3. User Account Responsibility',
      'body':
          'Users are responsible for providing accurate registration information and keeping their login credentials secure. Any action performed using a user’s account, such as saving projects, posting project requests, or requesting quotations, may be considered the responsibility of the account owner.',
    },
    {
      'title': '4. Project Posting and Quotation Requests',
      'body':
          'Users may post project details to request quotations from hardware shops. iConstruct only facilitates communication between users and hardware shops and does not guarantee that a quotation will be received, accepted, or completed.',
    },
    {
      'title': '5. Hardware Shop Product and Price Responsibility',
      'body':
          'Hardware shops are responsible for ensuring that the products, prices, availability, and quotations they provide are accurate and updated. Users are encouraged to confirm final prices, stock availability, delivery terms, and payment arrangements directly with the hardware shop.',
    },
    {
      'title': '6. No Direct Payment or Purchase Guarantee',
      'body':
          'iConstruct does not directly handle material purchases, payments, deliveries, refunds, or warranties unless such features are officially added in the future. Any transaction made outside the system is solely between the user and the hardware shop.',
    },
    {
      'title': '7. Proper Use of the Application',
      'body':
          'Users must not use iConstruct for fraudulent, misleading, abusive, or illegal activities. This includes submitting false project information, impersonating another user or shop, manipulating quotations, uploading harmful content, or attempting to damage or disrupt the system.',
    },
    {
      'title': '8. Data Privacy and User Information',
      'body':
          'iConstruct may collect and process user information such as account details, saved projects, selected materials, favorites, quotation requests, and location-related data to provide system features. User information should be handled according to applicable data privacy rules and used only for system-related purposes.',
    },
    {
      'title': '9. Account Suspension or Restriction',
      'body':
          'iConstruct reserves the right to suspend, restrict, or remove accounts that violate the system’s terms, provide false information, abuse platform features, fail to comply with shop subscription requirements, or create security risks for other users and the platform.',
    },
    {
      'title': '10. Limitation of Liability',
      'body':
          'iConstruct is not responsible for construction errors, incorrect purchases, project delays, price differences, supplier disputes, failed transactions, or damages caused by relying only on system-generated estimates. Users are responsible for confirming all project details with actual suppliers and qualified professionals before proceeding.',
    },
  ];

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _confirmPasswordController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  void _validateEmail(String value) {
    final trimmed = value.trim();
    const emailPattern = r'^[^@\s]+@[^@\s]+\.[^@\s]+$';

    setState(() {
      if (trimmed.isEmpty) {
        _emailError = 'Email is required';
      } else if (!RegExp(emailPattern).hasMatch(trimmed)) {
        _emailError = 'Enter a valid email address';
      } else {
        _emailError = null;
      }
    });
  }

  void _validatePassword(String value) {
    setState(() {
      _passwordError = PasswordPolicy.validate(value);
    });
  }

  void _validateConfirmPassword(String value) {
    setState(() {
      _confirmPasswordError = PasswordPolicy.validateConfirmation(
        _passwordController.text,
        value,
      );
    });
  }

  Future<void> _showTermsAndConditionsDialog() async {
    final accepted = await showDialog<bool>(
      context: context,
      barrierDismissible: false,
      builder: (_) => _TermsAndConditionsDialog(terms: _termsAndConditions),
    );

    if (accepted == true && mounted) {
      setState(() => _acceptedTerms = true);
    }
  }

  Future<void> _handleRegister() async {
    final firstName = _firstNameController.text.trim();
    final lastName = _lastNameController.text.trim();
    final email = _emailController.text.trim();
    final password = _passwordController.text;
    final confirmPassword = _confirmPasswordController.text;

    if (firstName.isEmpty ||
        lastName.isEmpty ||
        email.isEmpty ||
        password.isEmpty ||
        confirmPassword.isEmpty) {
      showAppMessage(context, const SnackBar(content: Text('All fields are required.')));
      return;
    }

    _validateEmail(email);
    _validatePassword(password);
    _validateConfirmPassword(confirmPassword);

    if (_emailError != null ||
        _passwordError != null ||
        _confirmPasswordError != null) {
      return;
    }

    if (!_acceptedTerms) {
      showAppMessage(context, 
        const SnackBar(
          content: Text('Please read and accept the Terms and Conditions.'),
        ),
      );
      return;
    }

    setState(() => _loading = true);

    try {
      debugPrint('Registration started');

      await _emailService.register(
        firstName: firstName,
        lastName: lastName,
        email: email,
        password: password,
      );

      if (!mounted) return;

      showAppMessage(
        context,
        const SnackBar(
          content: Text(
            'We sent a verification code. Your account is created after you enter it.',
          ),
        ),
        kind: AppMessageKind.success,
      );

      showDialog(
        context: context,
        barrierDismissible: false,
        builder: (_) => OtpDialog(
          email: email,
          firstName: firstName,
          lastName: lastName,
          password: password,
        ),
      );
    } catch (e) {
      if (!mounted) return;

      showAppMessage(context, 
        SnackBar(
          content: Text(stripAuthExceptionPrefix(e)),
        ),
      );
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Color(0xFF24384C), Color(0xFF35516F), Color(0xFF7FA4CC)],
            stops: [0, 0.62, 1],
          ),
        ),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.fromLTRB(24, 18, 24, 28),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  width: 40,
                  height: 40,
                  decoration: const BoxDecoration(
                    color: Color(0xFFF1E7D6),
                    shape: BoxShape.circle,
                  ),
                  child: IconButton(
                    padding: EdgeInsets.zero,
                    icon: const Icon(
                      Icons.arrow_back_ios_new_rounded,
                      size: 18,
                    ),
                    color: const Color(0xFF32465C),
                    onPressed: () => Navigator.of(context).maybePop(),
                  ),
                ),

                const SizedBox(height: 48),

                Expanded(
                  child: SingleChildScrollView(
                    controller: _scrollController,
                    padding: const EdgeInsets.only(bottom: 48),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Register',
                          style: GoogleFonts.poppins(
                            fontSize: 30,
                            fontWeight: FontWeight.w700,
                            color: Colors.white,
                          ),
                        ),

                        const SizedBox(height: 4),

                        Text(
                          'Create an account to start smart planning.',
                          style: GoogleFonts.poppins(
                            fontSize: 13,
                            fontWeight: FontWeight.w400,
                            color: const Color(0xFFB0C4D8),
                          ),
                        ),

                        const SizedBox(height: 22),

                        _RegisterField(
                          label: 'First Name',
                          controller: _firstNameController,
                          textInputAction: TextInputAction.next,
                        ),

                        const SizedBox(height: 12),

                        _RegisterField(
                          label: 'Last Name',
                          controller: _lastNameController,
                          textInputAction: TextInputAction.next,
                        ),

                        const SizedBox(height: 12),

                        _RegisterField(
                          label: 'Email',
                          controller: _emailController,
                          errorText: _emailError,
                          onChanged: _validateEmail,
                          keyboardType: TextInputType.emailAddress,
                          textInputAction: TextInputAction.next,
                        ),

                        const SizedBox(height: 12),

                        _RegisterField(
                          label: 'Password',
                          obscureText: _obscurePassword,
                          controller: _passwordController,
                          errorText: _passwordError,
                          onChanged: _validatePassword,
                          textInputAction: TextInputAction.next,
                          trailing: IconButton(
                            icon: Icon(
                              _obscurePassword
                                  ? Icons.visibility_off_rounded
                                  : Icons.visibility_rounded,
                              color: const Color(0xFF42566C),
                              size: 20,
                            ),
                            onPressed: () {
                              setState(
                                () => _obscurePassword = !_obscurePassword,
                              );
                            },
                          ),
                        ),

                        const SizedBox(height: 6),

                        Padding(
                          padding: const EdgeInsets.only(left: 4),
                          child: Text(
                            PasswordPolicy.hint,
                            style: GoogleFonts.inter(
                              color: const Color(0xFFE3D7C3),
                              fontSize: 12,
                              height: 1.4,
                            ),
                          ),
                        ),

                        const SizedBox(height: 12),

                        _RegisterField(
                          label: 'Confirm Password',
                          obscureText: _obscureConfirmPassword,
                          controller: _confirmPasswordController,
                          errorText: _confirmPasswordError,
                          onChanged: _validateConfirmPassword,
                          textInputAction: TextInputAction.done,
                          trailing: IconButton(
                            icon: Icon(
                              _obscureConfirmPassword
                                  ? Icons.visibility_off_rounded
                                  : Icons.visibility_rounded,
                              color: const Color(0xFF42566C),
                              size: 20,
                            ),
                            onPressed: () {
                              setState(
                                () => _obscureConfirmPassword =
                                    !_obscureConfirmPassword,
                              );
                            },
                          ),
                        ),

                        const SizedBox(height: 22),

                        Row(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Checkbox(
                              value: _acceptedTerms,
                              activeColor: const Color(0xFFF1E7D6),
                              checkColor: const Color(0xFF24384C),
                              side: const BorderSide(
                                color: Color(0xFFF1E7D6),
                                width: 1.5,
                              ),
                              onChanged: (value) {
                                setState(() {
                                  _acceptedTerms = value ?? false;
                                });
                              },
                            ),

                            Expanded(
                              child: Padding(
                                padding: const EdgeInsets.only(top: 10),
                                child: RichText(
                                  text: TextSpan(
                                    style: GoogleFonts.inter(
                                      fontSize: 12,
                                      color: const Color(0xFFB0C4D8),
                                      height: 1.4,
                                    ),
                                    children: [
                                      const TextSpan(
                                        text:
                                            'By registering, you agree to our ',
                                      ),
                                      TextSpan(
                                        text: 'Terms and Conditions',
                                        recognizer: TapGestureRecognizer()
                                          ..onTap =
                                              _showTermsAndConditionsDialog,
                                        style: GoogleFonts.inter(
                                          fontSize: 12,
                                          color: Colors.white,
                                          fontWeight: FontWeight.w700,
                                          decoration: TextDecoration.underline,
                                          decorationColor: Colors.white,
                                        ),
                                      ),
                                      const TextSpan(text: '.'),
                                    ],
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),

                        const SizedBox(height: 18),

                        SizedBox(
                          width: double.infinity,
                          height: 52,
                          child: TextButton(
                            style: TextButton.styleFrom(
                              backgroundColor: _acceptedTerms
                                  ? const Color(0xFF1E3248)
                                  : const Color(0xFF1E3248).withValues(alpha: 0.45),
                              foregroundColor: Colors.white,
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(14),
                              ),
                            ),
                            onPressed: _loading ? null : _handleRegister,
                            child: _loading
                                ? const SizedBox(
                                    height: 18,
                                    width: 18,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      valueColor: AlwaysStoppedAnimation(
                                        Colors.white,
                                      ),
                                    ),
                                  )
                                : Text(
                                    'Register',
                                    style: GoogleFonts.poppins(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w700,
                                    ),
                                  ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class _TermsAndConditionsDialog extends StatelessWidget {
  final List<Map<String, String>> terms;

  const _TermsAndConditionsDialog({required this.terms});

  @override
  Widget build(BuildContext context) {
    return Dialog(
      backgroundColor: const Color(0xFFF1E7D6),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(22)),
      child: Padding(
        padding: const EdgeInsets.fromLTRB(20, 18, 20, 16),
        child: SizedBox(
          width: double.infinity,
          height: 560,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  const Icon(
                    Icons.description_rounded,
                    color: Color(0xFF24384C),
                    size: 24,
                  ),

                  const SizedBox(width: 8),

                  Expanded(
                    child: Text(
                      'Terms and Conditions',
                      style: GoogleFonts.poppins(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                        color: const Color(0xFF24384C),
                      ),
                    ),
                  ),

                  IconButton(
                    onPressed: () => Navigator.of(context).pop(false),
                    icon: const Icon(
                      Icons.close_rounded,
                      color: Color(0xFF24384C),
                    ),
                  ),
                ],
              ),

              const SizedBox(height: 8),

              Text(
                'Please read the following conditions before continuing.',
                style: GoogleFonts.inter(
                  fontSize: 12,
                  fontWeight: FontWeight.w500,
                  color: const Color(0xFF617489),
                ),
              ),

              const SizedBox(height: 14),

              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    children: terms.map((term) {
                      return Container(
                        width: double.infinity,
                        margin: const EdgeInsets.only(bottom: 12),
                        padding: const EdgeInsets.all(14),
                        decoration: BoxDecoration(
                          color: Colors.white.withValues(alpha: 0.72),
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: const Color(0xFFD4C4AA)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              term['title'] ?? '',
                              style: GoogleFonts.poppins(
                                fontSize: 13.5,
                                fontWeight: FontWeight.w700,
                                color: const Color(0xFF24384C),
                              ),
                            ),

                            const SizedBox(height: 6),

                            Text(
                              term['body'] ?? '',
                              style: GoogleFonts.inter(
                                fontSize: 12,
                                height: 1.45,
                                color: const Color(0xFF3C4D5F),
                              ),
                            ),
                          ],
                        ),
                      );
                    }).toList(),
                  ),
                ),
              ),

              const SizedBox(height: 14),

              SizedBox(
                width: double.infinity,
                height: 46,
                child: TextButton(
                  onPressed: () => Navigator.of(context).pop(true),
                  style: TextButton.styleFrom(
                    backgroundColor: const Color(0xFF24384C),
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: Text(
                    'I Agree',
                    style: GoogleFonts.poppins(
                      fontSize: 14,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _RegisterField extends StatelessWidget {
  final String label;
  final bool obscureText;
  final Widget? trailing;
  final TextEditingController? controller;
  final String? errorText;
  final ValueChanged<String>? onChanged;
  final TextInputType? keyboardType;
  final TextInputAction? textInputAction;

  const _RegisterField({
    required this.label,
    this.obscureText = false,
    this.trailing,
    this.controller,
    this.errorText,
    this.onChanged,
    this.keyboardType,
    this.textInputAction,
  });

  @override
  Widget build(BuildContext context) {
    return TextField(
      controller: controller,
      obscureText: obscureText,
      onChanged: onChanged,
      keyboardType: keyboardType,
      textInputAction: textInputAction,
      style: GoogleFonts.inter(fontSize: 14, color: const Color(0xFF1E242B)),
      decoration: InputDecoration(
        hintText: label,
        hintStyle: GoogleFonts.poppins(
          color: const Color(0xFF6F665A),
          fontSize: 13.5,
          fontWeight: FontWeight.w500,
        ),
        filled: true,
        fillColor: const Color(0xFFE9DECC),
        suffixIcon: trailing,
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 18,
          vertical: 14,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0x00FFFFFF)),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(12),
          borderSide: const BorderSide(color: Color(0xFF8DB3E0), width: 1.5),
        ),
        error: warningFieldError(errorText),
        errorBorder: warningErrorBorder(),
        focusedErrorBorder: warningErrorBorder(width: 1.5),
      ),
    );
  }
}
