import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  static const List<Map<String, String>> _termsAndConditions = [
    {
      'title': '1. Purpose of iConstruct',
      'body':
          'iConstruct is a smart construction support system designed to help users plan basic residential construction projects through material estimation, cost estimation, project saving, supplier recommendations, and quotation support. The system is intended as a planning tool and should not replace professional construction, engineering, or architectural advice.',
    },
    {
      'title': '2. Accuracy of Material and Cost Estimates',
      'body':
          'All material quantities and cost estimates generated by iConstruct are for reference only. Actual construction costs may vary depending on supplier prices, labor costs, delivery fees, product availability, site conditions, and market changes. Users must verify estimates before making purchases or starting construction work.',
    },
    {
      'title': '3. User Account Responsibility',
      'body':
          'Users are responsible for providing accurate registration information and keeping their login credentials secure. Any action performed using a user’s account, such as saving projects, posting project requests, or requesting quotations, may be considered the responsibility of the account owner.',
    },
    {
      'title': '4. Project Posting and Quotation Requests',
      'body':
          'Users may post project details to request quotations from hardware shops. iConstruct only facilitates communication between users and hardware shops and does not guarantee that a quotation will be received, accepted, or completed.',
    },
    {
      'title': '5. Hardware Shop Product and Price Responsibility',
      'body':
          'Hardware shops are responsible for ensuring that the products, prices, availability, and quotations they provide are accurate and updated. Users are encouraged to confirm final prices, stock availability, delivery terms, and payment arrangements directly with the hardware shop.',
    },
    {
      'title': '6. No Direct Payment or Purchase Guarantee',
      'body':
          'iConstruct does not directly handle material purchases, payments, deliveries, refunds, or warranties unless such features are officially added in the future. Any transaction made outside the system is solely between the user and the hardware shop.',
    },
    {
      'title': '7. Proper Use of the Application',
      'body':
          'Users must not use iConstruct for fraudulent, misleading, abusive, or illegal activities. This includes submitting false project information, impersonating another user or shop, manipulating quotations, uploading harmful content, or attempting to damage or disrupt the system.',
    },
    {
      'title': '8. Data Privacy and User Information',
      'body':
          'iConstruct may collect and process user information such as account details, saved projects, selected materials, favorites, quotation requests, and location-related data to provide system features. User information should be handled according to applicable data privacy rules and used only for system-related purposes.',
    },
    {
      'title': '9. Account Suspension or Restriction',
      'body':
          'iConstruct reserves the right to suspend, restrict, or remove accounts that violate the system’s terms, provide false information, abuse platform features, fail to comply with shop subscription requirements, or create security risks for other users and the platform.',
    },
    {
      'title': '10. Limitation of Liability',
      'body':
          'iConstruct is not responsible for construction errors, incorrect purchases, project delays, price differences, supplier disputes, failed transactions, or damages caused by relying only on system-generated estimates. Users are responsible for confirming all project details with actual suppliers and qualified professionals before proceeding.',
    },
  ];

  @override
  Widget build(BuildContext context) {
    const cream = Color(0xFFEDE4D4);
    const darkBlue = Color(0xFF2C3E50);
    const midBlue = Color(0xFF648DB6);

    return Scaffold(
      backgroundColor: cream,
      appBar: AppBar(
        backgroundColor: cream,
        elevation: 0,
        leading: GestureDetector(
          onTap: () => Navigator.pop(context),
          child: Container(
            margin: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: Colors.white.withAlpha(128),
              shape: BoxShape.circle,
            ),
            child: const Icon(
              Icons.arrow_back_ios_new,
              color: darkBlue,
              size: 20,
            ),
          ),
        ),
        title: Text(
          'Terms & Conditions',
          style: GoogleFonts.poppins(
            color: darkBlue,
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: ListView.builder(
          padding: const EdgeInsets.fromLTRB(20, 20, 20, 32),
          itemCount: _termsAndConditions.length,
          itemBuilder: (context, index) {
            final term = _termsAndConditions[index];

            return Container(
              margin: const EdgeInsets.only(bottom: 14),
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(18),
                border: Border.all(color: midBlue.withAlpha(70), width: 1),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withAlpha(18),
                    blurRadius: 12,
                    offset: const Offset(0, 5),
                  ),
                ],
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    term['title'] ?? '',
                    style: GoogleFonts.poppins(
                      fontSize: 15,
                      fontWeight: FontWeight.w700,
                      color: darkBlue,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    term['body'] ?? '',
                    style: GoogleFonts.poppins(
                      fontSize: 13,
                      height: 1.55,
                      color: const Color(0xFF4D5F70),
                    ),
                  ),
                ],
              ),
            );
          },
        ),
      ),
    );
  }
}
