// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4hyvv3ZtGWs0XmpeRgkIsJloFvahc6LI',
    appId: '1:244045941716:web:3a6b24865a2f29d7606441',
    messagingSenderId: '244045941716',
    projectId: 'iconstruct-58a87',
    authDomain: 'iconstruct-58a87.firebaseapp.com',
    storageBucket: 'iconstruct-58a87.firebasestorage.app',
    measurementId: 'G-527KSF5D03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5gembaurNYI-Lb4Tzfsa9TKsl0-gFAY8',
    appId: '1:244045941716:android:f501eff78dc3ff22606441',
    messagingSenderId: '244045941716',
    projectId: 'iconstruct-58a87',
    storageBucket: 'iconstruct-58a87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQaI0VmOuIRymLA9ekNK3AC3lh3oqbw4k',
    appId: '1:244045941716:ios:c726adb71113b822606441',
    messagingSenderId: '244045941716',
    projectId: 'iconstruct-58a87',
    storageBucket: 'iconstruct-58a87.firebasestorage.app',
    iosBundleId: 'com.example.iconstruct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQaI0VmOuIRymLA9ekNK3AC3lh3oqbw4k',
    appId: '1:244045941716:ios:c726adb71113b822606441',
    messagingSenderId: '244045941716',
    projectId: 'iconstruct-58a87',
    storageBucket: 'iconstruct-58a87.firebasestorage.app',
    iosBundleId: 'com.example.iconstruct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4hyvv3ZtGWs0XmpeRgkIsJloFvahc6LI',
    appId: '1:244045941716:web:8380c2efaff6057f606441',
    messagingSenderId: '244045941716',
    projectId: 'iconstruct-58a87',
    authDomain: 'iconstruct-58a87.firebaseapp.com',
    storageBucket: 'iconstruct-58a87.firebasestorage.app',
    measurementId: 'G-677H5L90B1',
  );
}
